package by.xo.egorp.finance.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "WALLET_ICON".
 */
@Entity
public class WalletIcon {

    @Id(autoincrement = true)
    private Long id;
    private Integer walletPic;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public WalletIcon() {
    }

    public WalletIcon(Long id) {
        this.id = id;
    }

    @Generated
    public WalletIcon(Long id, Integer walletPic) {
        this.id = id;
        this.walletPic = walletPic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getWalletPic() {
        return walletPic;
    }

    public void setWalletPic(Integer walletPic) {
        this.walletPic = walletPic;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
